package de.tipau.promille.ui.components

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.graphics.vector.rememberVectorPainter
import androidx.compose.ui.res.painterResource
import de.tipau.promille.R
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

// Hand-drawn Material geometry for the 22 symbols the SF dump has no glyph for.
// Everything else went to real SF artwork, so nothing here is a fallback anyone
// can reach except through AppIcons below.
internal object AppVectors {

    private fun buildIcon(
        name: String,
        block: androidx.compose.ui.graphics.vector.PathBuilder.() -> Unit
    ): ImageVector {
        return ImageVector.Builder(
            name = name,
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 24f,
            viewportHeight = 24f
        ).apply {
            path(fill = SolidColor(Color.White)) {
                block()
            }
        }.build()
    }

    val Taxi: ImageVector = buildIcon("Taxi") {
        moveTo(18.92f, 6.01f)
        curveTo(18.72f, 5.42f, 18.16f, 5f, 17.5f, 5f)
        horizontalLineToRelative(-1f)
        verticalLineTo(3f)
        horizontalLineToRelative(-3f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-3f)
        verticalLineTo(3f)
        horizontalLineTo(7.5f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(-1f)
        curveToRelative(-0.66f, 0f, -1.21f, 0.42f, -1.42f, 1.01f)
        lineTo(3f, 12f)
        verticalLineToRelative(8f)
        curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
        horizontalLineToRelative(1f)
        curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
        verticalLineToRelative(-1f)
        horizontalLineToRelative(12f)
        verticalLineToRelative(1f)
        curveToRelative(0f, 0.55f, 0.45f, 1f, 1f, 1f)
        horizontalLineToRelative(1f)
        curveToRelative(0.55f, 0f, 1f, -0.45f, 1f, -1f)
        verticalLineToRelative(-8f)
        lineToRelative(-2.08f, -5.99f)
        close()
    }

    val Pill: ImageVector = buildIcon("Pill") {
        moveTo(6f, 3f)
        horizontalLineToRelative(12f)
        curveToRelative(1.66f, 0f, 3f, 1.34f, 3f, 3f)
        verticalLineToRelative(12f)
        curveToRelative(0f, 1.66f, -1.34f, 3f, -3f, 3f)
        horizontalLineTo(6f)
        curveToRelative(-1.66f, 0f, -3f, -1.34f, -3f, -3f)
        verticalLineTo(6f)
        curveToRelative(0f, -1.66f, 1.34f, -3f, 3f, -3f)
        close()
        moveTo(4.5f, 11f)
        horizontalLineToRelative(15f)
        verticalLineTo(6f)
        curveToRelative(0f, -0.83f, -0.67f, -1.5f, -1.5f, -1.5f)
        horizontalLineTo(6f)
        curveToRelative(-0.83f, 0f, -1.5f, 0.67f, -1.5f, 1.5f)
        verticalLineToRelative(5f)
        close()
    }

    val Water: ImageVector = buildIcon("Water") {
        moveTo(12f, 20f)
        curveToRelative(-3.31f, 0f, -6f, -2.69f, -6f, -6f)
        curveToRelative(0f, -3.31f, 6f, -10f, 6f, -10f)
        reflectiveCurveToRelative(6f, 6.69f, 6f, 10f)
        curveToRelative(0f, 3.31f, -2.69f, 6f, -6f, 6f)
        close()
    }

    val Drink: ImageVector = buildIcon("Drink") {
        moveTo(21f, 5f)
        verticalLineTo(4f)
        horizontalLineTo(3f)
        verticalLineToRelative(1f)
        lineToRelative(8f, 9f)
        verticalLineToRelative(6f)
        horizontalLineTo(6f)
        verticalLineToRelative(2f)
        horizontalLineToRelative(12f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(-5f)
        verticalLineToRelative(-6f)
        lineToRelative(8f, -9f)
        close()
        moveTo(7.43f, 7f)
        lineTo(5.66f, 5f)
        horizontalLineToRelative(12.69f)
        lineToRelative(-1.78f, 2f)
        horizontalLineTo(7.43f)
        close()
    }
        
    val Bottle: ImageVector = buildIcon("Bottle") {
        moveTo(14f, 7f)
        verticalLineTo(4f)
        curveToRelative(0f, -1.1f, -0.9f, -2f, -2f, -2f)
        reflectiveCurveToRelative(-2f, 0.9f, -2f, 2f)
        verticalLineToRelative(3f)
        curveToRelative(-1.66f, 0f, -3f, 1.34f, -3f, 3f)
        verticalLineToRelative(10f)
        curveToRelative(0f, 1.1f, 0.9f, 2f, 2f, 2f)
        horizontalLineToRelative(6f)
        curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
        verticalLineTo(10f)
        curveToRelative(0f, -1.66f, -1.34f, -3f, -3f, -3f)
        close()
    }
        
    val Beer: ImageVector = buildIcon("Beer") {
        moveTo(20f, 6f)
        horizontalLineToRelative(-2.18f)
        curveToRelative(0.11f, -0.31f, 0.18f, -0.65f, 0.18f, -1f)
        curveToRelative(0f, -1.66f, -1.34f, -3f, -3f, -3f)
        curveToRelative(-1.05f, 0f, -1.96f, 0.54f, -2.5f, 1.35f)
        lineToRelative(-0.5f, -0.67f)
        curveTo(11.38f, 1.86f, 10.27f, 1.31f, 9f, 1.31f)
        curveTo(7.1f, 1.31f, 5.51f, 2.76f, 5.11f, 4.6f)
        curveTo(4.45f, 4.88f, 4f, 5.53f, 4f, 6.31f)
        verticalLineTo(20f)
        curveToRelative(0f, 1.1f, 0.9f, 2f, 2f, 2f)
        horizontalLineToRelative(10f)
        curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
        verticalLineToRelative(-3f)
        horizontalLineToRelative(2f)
        curveToRelative(1.11f, 0f, 2f, -0.89f, 2f, -2f)
        verticalLineTo(8f)
        curveToRelative(0f, -1.11f, -0.89f, -2f, -2f, -2f)
        close()
        moveTo(20f, 15f)
        horizontalLineToRelative(-2f)
        verticalLineTo(8f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(7f)
        close()
    }
        
    val Wine: ImageVector = buildIcon("Wine") {
        moveTo(6f, 2f)
        horizontalLineToRelative(12f)
        verticalLineToRelative(3f)
        lineToRelative(-4f, 5f)
        verticalLineToRelative(10f)
        horizontalLineToRelative(3f)
        verticalLineToRelative(2f)
        horizontalLineTo(7f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(3f)
        verticalLineTo(10f)
        lineTo(6f, 5f)
        verticalLineTo(2f)
        close()
        moveTo(14.6f, 5f)
        horizontalLineTo(9.4f)
        lineToRelative(-1.6f, 2f)
        horizontalLineToRelative(8.4f)
        lineToRelative(-1.6f, -2f)
        close()
    }

    val Shot: ImageVector = buildIcon("Shot") {
        moveTo(8f, 2f)
        horizontalLineToRelative(8f)
        verticalLineToRelative(2f)
        lineToRelative(-1f, 16f)
        horizontalLineTo(9f)
        lineTo(8f, 4f)
        verticalLineTo(2f)
        close()
    }
        
    val Restaurant: ImageVector = buildIcon("Restaurant") {
        moveTo(16f, 6f)
        verticalLineToRelative(8f)
        horizontalLineToRelative(3f)
        verticalLineToRelative(8f)
        horizontalLineToRelative(2f)
        verticalLineTo(2f)
        curveToRelative(-2.76f, 0f, -5f, 2.24f, -5f, 4f)
        close()
        moveTo(11f, 9f)
        horizontalLineTo(9f)
        verticalLineTo(2f)
        horizontalLineTo(7f)
        verticalLineToRelative(7f)
        horizontalLineTo(5f)
        verticalLineTo(2f)
        horizontalLineTo(3f)
        verticalLineToRelative(7f)
        curveToRelative(0f, 2.21f, 1.79f, 4f, 4f, 4f)
        verticalLineToRelative(9f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(-9f)
        curveToRelative(2.21f, 0f, 4f, -1.79f, 4f, -4f)
        verticalLineTo(2f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(7f)
        close()
    }

    val TouchApp: ImageVector = buildIcon("TouchApp") {
        moveTo(9f, 11.24f)
        verticalLineTo(7.5f)
        curveTo(9f, 6.12f, 10.12f, 5f, 11.5f, 5f)
        reflectiveCurveTo(14f, 6.12f, 14f, 7.5f)
        verticalLineToRelative(3.74f)
        curveToRelative(1.21f, -0.81f, 2f, -2.18f, 2f, -3.74f)
        curveTo(16f, 5.01f, 13.99f, 3f, 11.5f, 3f)
        reflectiveCurveTo(7f, 5.01f, 7f, 7.5f)
        curveToRelative(0f, 1.56f, 0.79f, 2.93f, 2f, 3.74f)
        close()
        moveTo(18.84f, 15.87f)
        lineToRelative(-4.54f, -2.26f)
        curveToRelative(-0.17f, -0.07f, -0.35f, -0.11f, -0.54f, -0.11f)
        horizontalLineTo(13f)
        verticalLineToRelative(-6f)
        curveToRelative(0f, -0.83f, -0.67f, -1.5f, -1.5f, -1.5f)
        reflectiveCurveTo(10f, 6.67f, 10f, 7.5f)
        verticalLineToRelative(10.74f)
        lineToRelative(-3.43f, -0.72f)
        curveToRelative(-0.08f, -0.01f, -0.15f, -0.03f, -0.24f, -0.03f)
        curveToRelative(-0.31f, 0f, -0.59f, 0.13f, -0.79f, 0.33f)
        lineToRelative(-0.79f, 0.8f)
        lineToRelative(4.94f, 4.94f)
        curveToRelative(0.27f, 0.27f, 0.65f, 0.44f, 1.04f, 0.44f)
        horizontalLineToRelative(6.79f)
        curveToRelative(0.75f, 0f, 1.33f, -0.55f, 1.44f, -1.28f)
        lineToRelative(0.75f, -5.27f)
        curveToRelative(0.01f, -0.07f, 0.02f, -0.14f, 0.02f, -0.2f)
        curveToRelative(0f, -0.62f, -0.38f, -1.16f, -0.91f, -1.38f)
        close()
    }

    val RadioWaveSlash: ImageVector = buildIcon("RadioWaveSlash") {
        moveTo(12f, 12f)
        curveToRelative(-1.1f, 0f, -2f, 0.9f, -2f, 2f)
        reflectiveCurveToRelative(0.9f, 2f, 2f, 2f)
        reflectiveCurveToRelative(2f, -0.9f, 2f, -2f)
        reflectiveCurveToRelative(-0.9f, -2f, -2f, -2f)
        close()
        moveTo(4.93f, 4.93f)
        lineTo(3.51f, 3.51f)
        curveTo(1.36f, 5.67f, 0f, 8.68f, 0f, 12f)
        reflectiveCurveToRelative(1.36f, 6.33f, 3.51f, 8.49f)
        lineToRelative(1.42f, -1.42f)
        curveTo(3.18f, 17.31f, 2f, 14.8f, 2f, 12f)
        reflectiveCurveToRelative(1.18f, -5.31f, 2.93f, -7.07f)
        close()
        moveTo(20.49f, 3.51f)
        lineToRelative(-1.42f, 1.42f)
        curveTo(20.82f, 6.69f, 22f, 9.2f, 22f, 12f)
        reflectiveCurveToRelative(-1.18f, 5.31f, -2.93f, 7.07f)
        lineToRelative(1.42f, 1.42f)
        curveTo(22.64f, 18.33f, 24f, 15.32f, 24f, 12f)
        reflectiveCurveToRelative(-1.36f, -6.33f, -3.51f, -8.49f)
        close()
        // Diagonal slash, corner to corner.
        moveTo(1.22f, 21.22f)
        lineTo(2.78f, 22.78f)
        lineTo(22.78f, 2.78f)
        lineTo(21.22f, 1.22f)
        close()
    }

    /** eye.slash.fill: a solid eye silhouette, crossed out. */
    val PersonQuestionMark: ImageVector = buildIcon("PersonQuestionMark") {
        // Head, shifted left to leave room for the "?" on the right.
        moveTo(9f, 11f)
        curveToRelative(1.93f, 0f, 3.5f, -1.57f, 3.5f, -3.5f)
        reflectiveCurveTo(10.93f, 4f, 9f, 4f)
        reflectiveCurveTo(5.5f, 5.57f, 5.5f, 7.5f)
        reflectiveCurveTo(7.07f, 11f, 9f, 11f)
        close()
        // Shoulders
        moveTo(9f, 13f)
        curveToRelative(-2.34f, 0f, -7f, 1.17f, -7f, 3.5f)
        verticalLineTo(19f)
        horizontalLineToRelative(14f)
        verticalLineToRelative(-2.5f)
        curveToRelative(0f, -2.33f, -4.66f, -3.5f, -7f, -3.5f)
        close()
        // Question mark hook
        moveTo(16.4f, 4.9f)
        curveToRelative(0f, -1.16f, 0.94f, -2.1f, 2.1f, -2.1f)
        reflectiveCurveToRelative(2.1f, 0.94f, 2.1f, 2.1f)
        curveToRelative(0f, 1.13f, -0.77f, 1.63f, -1.42f, 2.09f)
        curveToRelative(-0.55f, 0.39f, -0.98f, 0.75f, -0.98f, 1.51f)
        horizontalLineToRelative(-1.4f)
        curveToRelative(0f, -1.24f, 0.62f, -1.76f, 1.19f, -2.16f)
        curveToRelative(0.5f, -0.36f, 0.91f, -0.65f, 0.91f, -1.44f)
        curveToRelative(0f, -0.39f, -0.32f, -0.7f, -0.7f, -0.7f)
        reflectiveCurveToRelative(-0.7f, 0.31f, -0.7f, 0.7f)
        horizontalLineTo(16.4f)
        close()
        moveTo(17.8f, 9.3f)
        horizontalLineToRelative(1.4f)
        verticalLineToRelative(1.4f)
        horizontalLineToRelative(-1.4f)
        close()
    }

    /**
     * xmark.circle.fill. Not in material-icons-core (only the extended
     * artifact this project doesn't depend on has Cancel), so hand-built:
     * a filled circle with the X cut out, same EvenOdd technique
     * StatusPill.kt's XOctagon uses.
     */
    val Building: ImageVector = buildIcon("Building") {
        moveTo(12f, 7f)
        verticalLineTo(3f)
        horizontalLineTo(2f)
        verticalLineToRelative(18f)
        horizontalLineToRelative(20f)
        verticalLineTo(7f)
        horizontalLineTo(12f)
        close()
        moveTo(6f, 19f)
        horizontalLineTo(4f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        close()
        moveTo(6f, 15f)
        horizontalLineTo(4f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        close()
        moveTo(6f, 11f)
        horizontalLineTo(4f)
        verticalLineTo(9f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        close()
        moveTo(6f, 7f)
        horizontalLineTo(4f)
        verticalLineTo(5f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        close()
        moveTo(10f, 19f)
        horizontalLineTo(8f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        close()
        moveTo(10f, 15f)
        horizontalLineTo(8f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        close()
        moveTo(10f, 11f)
        horizontalLineTo(8f)
        verticalLineTo(9f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        close()
        moveTo(10f, 7f)
        horizontalLineTo(8f)
        verticalLineTo(5f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(2f)
        close()
        moveTo(20f, 19f)
        horizontalLineToRelative(-8f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(-2f)
        verticalLineTo(9f)
        horizontalLineToRelative(8f)
        verticalLineToRelative(10f)
        close()
    }

    val Crown: ImageVector = buildIcon("Crown") {
        moveTo(3f, 18f)
        lineTo(3f, 7f)
        lineTo(8f, 12f)
        lineTo(12f, 4f)
        lineTo(16f, 12f)
        lineTo(21f, 7f)
        lineTo(21f, 18f)
        close()
    }

    /** person.fill.xmark: the "remove participant" action. */
    val Key: ImageVector = buildIcon("Key") {
        moveTo(12.65f, 10f)
        curveTo(11.83f, 7.67f, 9.61f, 6f, 7f, 6f)
        curveToRelative(-3.31f, 0f, -6f, 2.69f, -6f, 6f)
        reflectiveCurveToRelative(2.69f, 6f, 6f, 6f)
        curveToRelative(2.61f, 0f, 4.83f, -1.67f, 5.65f, -4f)
        horizontalLineTo(17f)
        verticalLineToRelative(4f)
        horizontalLineToRelative(4f)
        verticalLineToRelative(-4f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(-4f)
        horizontalLineTo(12.65f)
        close()
        moveTo(7f, 14f)
        curveToRelative(-1.1f, 0f, -2f, -0.9f, -2f, -2f)
        reflectiveCurveToRelative(0.9f, -2f, 2f, -2f)
        reflectiveCurveToRelative(2f, 0.9f, 2f, 2f)
        reflectiveCurveToRelative(-0.9f, 2f, -2f, 2f)
        close()
    }

    val FigureStand: ImageVector = buildIcon("FigureStand") {
        // Head
        moveTo(12f, 1.9f)
        curveTo(13.05f, 1.9f, 13.9f, 2.75f, 13.9f, 3.8f)
        reflectiveCurveTo(13.05f, 5.7f, 12f, 5.7f)
        reflectiveCurveTo(10.1f, 4.85f, 10.1f, 3.8f)
        reflectiveCurveTo(10.95f, 1.9f, 12f, 1.9f)
        close()

        // Left arm
        moveTo(6.7f, 7.6f)
        curveTo(6.31f, 7.6f, 6.0f, 7.91f, 6.0f, 8.3f)
        verticalLineToRelative(5.5f)
        curveToRelative(0f, 0.39f, 0.31f, 0.7f, 0.7f, 0.7f)
        reflectiveCurveToRelative(0.7f, -0.31f, 0.7f, -0.7f)
        verticalLineToRelative(-5.5f)
        curveToRelative(0f, -0.39f, -0.31f, -0.7f, -0.7f, -0.7f)
        close()

        // Right arm
        moveTo(17.3f, 7.6f)
        curveTo(16.91f, 7.6f, 16.6f, 7.91f, 16.6f, 8.3f)
        verticalLineToRelative(5.5f)
        curveToRelative(0f, 0.39f, 0.31f, 0.7f, 0.7f, 0.7f)
        reflectiveCurveToRelative(0.7f, -0.31f, 0.7f, -0.7f)
        verticalLineToRelative(-5.5f)
        curveToRelative(0f, -0.39f, -0.31f, -0.7f, -0.7f, -0.7f)
        close()

        // Torso & Left Leg & Right Leg
        moveTo(9.6f, 7.6f)
        horizontalLineToRelative(4.8f)
        curveToRelative(0.44f, 0f, 0.8f, 0.36f, 0.8f, 0.8f)
        verticalLineToRelative(13.0f)
        curveToRelative(0f, 0.44f, -0.36f, 0.8f, -0.8f, 0.8f)
        reflectiveCurveToRelative(-0.8f, -0.36f, -0.8f, -0.8f)
        verticalLineToRelative(-6.9f)
        horizontalLineToRelative(-1.6f)
        verticalLineToRelative(6.9f)
        curveToRelative(0f, 0.44f, -0.36f, 0.8f, -0.8f, 0.8f)
        reflectiveCurveToRelative(-0.8f, -0.36f, -0.8f, -0.8f)
        verticalLineTo(8.4f)
        curveToRelative(0f, -0.44f, 0.36f, -0.8f, 0.8f, -0.8f)
        close()
    }

    val FigureStandDress: ImageVector = buildIcon("FigureStandDress") {
        // Head
        moveTo(12f, 1.9f)
        curveTo(13.05f, 1.9f, 13.9f, 2.75f, 13.9f, 3.8f)
        reflectiveCurveTo(13.05f, 5.7f, 12f, 5.7f)
        reflectiveCurveTo(10.1f, 4.85f, 10.1f, 3.8f)
        reflectiveCurveTo(10.95f, 1.9f, 12f, 1.9f)
        close()

        // Left arm (angled along dress)
        moveTo(6.8f, 7.6f)
        curveTo(6.45f, 7.45f, 6.05f, 7.65f, 5.9f, 8.0f)
        lineToRelative(-1.4f, 5.4f)
        curveTo(4.35f, 13.75f, 4.55f, 14.15f, 4.9f, 14.3f)
        curveToRelative(0.35f, 0.15f, 0.75f, -0.05f, 0.9f, -0.4f)
        lineToRelative(1.4f, -5.4f)
        curveTo(7.35f, 8.15f, 7.15f, 7.75f, 6.8f, 7.6f)
        close()

        // Right arm (angled along dress)
        moveTo(17.2f, 7.6f)
        curveTo(16.85f, 7.75f, 16.65f, 8.15f, 16.8f, 8.5f)
        lineToRelative(1.4f, 5.4f)
        curveToRelative(0.15f, 0.35f, 0.55f, 0.55f, 0.9f, 0.4f)
        curveToRelative(0.35f, -0.15f, 0.55f, -0.55f, 0.4f, -0.9f)
        lineToRelative(-1.4f, -5.4f)
        curveTo(17.95f, 7.65f, 17.55f, 7.45f, 17.2f, 7.6f)
        close()

        // Dress
        moveTo(9.8f, 7.6f)
        horizontalLineToRelative(4.4f)
        curveToRelative(0.44f, 0f, 0.8f, 0.36f, 0.8f, 0.8f)
        lineToRelative(2.2f, 7.3f)
        curveToRelative(0.12f, 0.4f, -0.18f, 0.8f, -0.6f, 0.8f)
        horizontalLineTo(7.4f)
        curveToRelative(-0.42f, 0f, -0.72f, -0.4f, -0.6f, -0.8f)
        lineToRelative(2.2f, -7.3f)
        curveTo(9.0f, 7.96f, 9.36f, 7.6f, 9.8f, 7.6f)
        close()

        // Left leg
        moveTo(10.1f, 16.5f)
        verticalLineToRelative(4.9f)
        curveToRelative(0f, 0.44f, -0.36f, 0.8f, -0.8f, 0.8f)
        reflectiveCurveToRelative(-0.8f, -0.36f, -0.8f, -0.8f)
        verticalLineToRelative(-4.9f)
        horizontalLineToRelative(1.6f)
        close()

        // Right leg
        moveTo(14.7f, 16.5f)
        verticalLineToRelative(4.9f)
        curveToRelative(0f, 0.44f, -0.36f, 0.8f, -0.8f, 0.8f)
        reflectiveCurveToRelative(-0.8f, -0.36f, -0.8f, -0.8f)
        verticalLineToRelative(-4.9f)
        horizontalLineToRelative(1.6f)
        close()
    }

    val Drop: ImageVector = buildIcon("Drop") {
        moveTo(12f, 2.69f)
        lineToRelative(5.66f, 5.66f)
        arcToRelative(8f, 8f, 0f, true, true, -11.31f, 0f)
        close()
    }

    val Dice: ImageVector = buildIcon("Dice") {
        moveTo(19f, 3f)
        horizontalLineTo(5f)
        curveToRelative(-1.1f, 0f, -2f, 0.9f, -2f, 2f)
        verticalLineToRelative(14f)
        curveToRelative(0f, 1.1f, 0.9f, 2f, 2f, 2f)
        horizontalLineToRelative(14f)
        curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
        verticalLineTo(5f)
        curveToRelative(0f, -1.1f, -0.9f, -2f, -2f, -2f)
        close()
        // Top-left dot
        moveTo(7.5f, 9f)
        curveToRelative(-0.83f, 0f, -1.5f, -0.67f, -1.5f, -1.5f)
        reflectiveCurveTo(6.67f, 6f, 7.5f, 6f)
        reflectiveCurveToRelative(1.5f, 0.67f, 1.5f, 1.5f)
        reflectiveCurveTo(8.33f, 9f, 7.5f, 9f)
        close()
        // Center dot
        moveTo(12f, 13.5f)
        curveToRelative(-0.83f, 0f, -1.5f, -0.67f, -1.5f, -1.5f)
        reflectiveCurveToRelative(0.67f, -1.5f, 1.5f, -1.5f)
        reflectiveCurveToRelative(1.5f, 0.67f, 1.5f, 1.5f)
        reflectiveCurveToRelative(-0.67f, 1.5f, -1.5f, 1.5f)
        close()
        // Bottom-right dot
        moveTo(16.5f, 18f)
        curveToRelative(-0.83f, 0f, -1.5f, -0.67f, -1.5f, -1.5f)
        reflectiveCurveToRelative(0.67f, -1.5f, 1.5f, -1.5f)
        reflectiveCurveToRelative(1.5f, 0.67f, 1.5f, 1.5f)
        reflectiveCurveToRelative(-0.67f, 1.5f, -1.5f, 1.5f)
        close()
    }

    val Mug: ImageVector = buildIcon("Mug") {
        moveTo(17f, 5f)
        verticalLineTo(3f)
        horizontalLineTo(5f)
        verticalLineToRelative(14f)
        curveToRelative(0f, 2.21f, 1.79f, 4f, 4f, 4f)
        horizontalLineToRelative(4f)
        curveToRelative(2.21f, 0f, 4f, -1.79f, 4f, -4f)
        verticalLineToRelative(-2f)
        horizontalLineToRelative(2f)
        curveToRelative(1.66f, 0f, 3f, -1.34f, 3f, -3f)
        verticalLineTo(8f)
        curveToRelative(0f, -1.66f, -1.34f, -3f, -3f, -3f)
        horizontalLineToRelative(-2f)
        close()
        moveTo(19f, 12f)
        curveToRelative(0f, 0.55f, -0.45f, 1f, -1f, 1f)
        horizontalLineToRelative(-1f)
        verticalLineTo(7f)
        horizontalLineToRelative(1f)
        curveToRelative(0.55f, 0f, 1f, 0.45f, 1f, 1f)
        verticalLineToRelative(4f)
        close()
    }

    val Cup: ImageVector = buildIcon("Cup") {
        moveTo(20f, 3f)
        horizontalLineTo(4f)
        verticalLineToRelative(10f)
        curveToRelative(0f, 2.21f, 1.79f, 4f, 4f, 4f)
        horizontalLineToRelative(6f)
        curveToRelative(2.21f, 0f, 4f, -1.79f, 4f, -4f)
        verticalLineToRelative(-3f)
        horizontalLineToRelative(2f)
        curveToRelative(1.1f, 0f, 2f, -0.9f, 2f, -2f)
        verticalLineTo(5f)
        curveToRelative(0f, -1.1f, -0.9f, -2f, -2f, -2f)
        close()
        moveTo(20f, 8f)
        horizontalLineToRelative(-2f)
        verticalLineTo(5f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(3f)
        close()
        moveTo(2f, 19f)
        horizontalLineToRelative(20f)
        verticalLineToRelative(2f)
        horizontalLineTo(2f)
        close()
    }

    val ForkKnife: ImageVector = buildIcon("ForkKnife") {
        moveTo(11f, 9f)
        horizontalLineTo(9f)
        verticalLineTo(2f)
        horizontalLineTo(7f)
        verticalLineToRelative(7f)
        horizontalLineTo(5f)
        verticalLineTo(2f)
        horizontalLineTo(3f)
        verticalLineToRelative(7f)
        curveToRelative(0f, 2.21f, 1.79f, 4f, 4f, 4f)
        verticalLineToRelative(9f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(-9f)
        curveToRelative(2.21f, 0f, 4f, -1.79f, 4f, -4f)
        verticalLineTo(2f)
        horizontalLineToRelative(-2f)
        verticalLineToRelative(7f)
        close()
        moveTo(19f, 2f)
        curveToRelative(-2.21f, 0f, -4f, 1.79f, -4f, 4f)
        verticalLineToRelative(6f)
        horizontalLineToRelative(2f)
        verticalLineToRelative(10f)
        horizontalLineToRelative(2f)
        verticalLineTo(2f)
        horizontalLineToRelative(-0f)
        close()
    }

}

// iOS draws every one of these as an SF Symbol. 54 of them use the real artwork
// (imported by tools/sf_import.py); the other 22 fall back to AppVectors, since
// the dump is an SF 1.0/2.0 set and the drink, food and reward symbols this app
// leans on (wineglass, waterbottle, cup.and.saucer, fork.knife, trophy, crown,
// drop) all arrived in SF 3, with nothing close enough to stand in.
object AppIcons {
    val Minus: Painter @Composable get() = painterResource(R.drawable.sf_minus)
    val Car: Painter @Composable get() = painterResource(R.drawable.sf_car_fill)
    val Taxi: Painter @Composable get() = rememberVectorPainter(AppVectors.Taxi)
    val Train: Painter @Composable get() = painterResource(R.drawable.sf_tram_fill)
    val Phone: Painter @Composable get() = painterResource(R.drawable.sf_phone_fill)
    val Pill: Painter @Composable get() = rememberVectorPainter(AppVectors.Pill)
    val Water: Painter @Composable get() = rememberVectorPainter(AppVectors.Water)
    val Fire: Painter @Composable get() = painterResource(R.drawable.sf_flame_fill)
    val Sun: Painter @Composable get() = painterResource(R.drawable.sf_sun_max_fill)
    val Shield: Painter @Composable get() = painterResource(R.drawable.sf_shield_fill)
    val Group: Painter @Composable get() = painterResource(R.drawable.sf_person_2_fill)
    val Lock: Painter @Composable get() = painterResource(R.drawable.sf_lock_fill)
    val Chart: Painter @Composable get() = painterResource(R.drawable.sf_chart_bar_fill)
    val Pencil: Painter @Composable get() = painterResource(R.drawable.sf_pencil)
    val Bolt: Painter @Composable get() = painterResource(R.drawable.sf_bolt_fill)
    val Settings: Painter @Composable get() = painterResource(R.drawable.sf_gear)
    val Drink: Painter @Composable get() = rememberVectorPainter(AppVectors.Drink)
    val Bottle: Painter @Composable get() = rememberVectorPainter(AppVectors.Bottle)
    val Beer: Painter @Composable get() = rememberVectorPainter(AppVectors.Beer)
    val Wine: Painter @Composable get() = rememberVectorPainter(AppVectors.Wine)
    val Shot: Painter @Composable get() = rememberVectorPainter(AppVectors.Shot)
    val EmojiEvents: Painter @Composable get() = painterResource(R.drawable.sf_rosette)
    val Restaurant: Painter @Composable get() = rememberVectorPainter(AppVectors.Restaurant)
    val TouchApp: Painter @Composable get() = rememberVectorPainter(AppVectors.TouchApp)
    val Copy: Painter @Composable get() = painterResource(R.drawable.sf_doc_on_doc)
    val Expand: Painter @Composable get() = painterResource(R.drawable.sf_arrow_up_left_and_arrow_down_right)
    val House: Painter @Composable get() = painterResource(R.drawable.sf_house_fill)
    val Person: Painter @Composable get() = painterResource(R.drawable.sf_person_fill)
    val Share: Painter @Composable get() = painterResource(R.drawable.sf_square_and_arrow_up)
    val Close: Painter @Composable get() = painterResource(R.drawable.sf_xmark)
    val Check: Painter @Composable get() = painterResource(R.drawable.sf_checkmark)
    val Info: Painter @Composable get() = painterResource(R.drawable.sf_info_circle)
    val Bell: Painter @Composable get() = painterResource(R.drawable.sf_bell_fill)
    val Trash: Painter @Composable get() = painterResource(R.drawable.sf_trash)
    val ExitToApp: Painter @Composable get() = painterResource(R.drawable.sf_arrow_right_square)
    val Undo: Painter @Composable get() = painterResource(R.drawable.sf_arrow_uturn_left_circle_fill)
    val ChevronRight: Painter @Composable get() = painterResource(R.drawable.sf_chevron_right)
    val ChevronDown: Painter @Composable get() = painterResource(R.drawable.sf_chevron_down)
    val ChevronUp: Painter @Composable get() = painterResource(R.drawable.sf_chevron_up)
    val TextFormat: Painter @Composable get() = painterResource(R.drawable.sf_textformat)
    val Photo: Painter @Composable get() = painterResource(R.drawable.sf_photo)
    val RadioWave: Painter @Composable get() = painterResource(R.drawable.sf_antenna_radiowaves_left_and_right)
    val RadioWaveSlash: Painter @Composable get() = rememberVectorPainter(AppVectors.RadioWaveSlash)
    val EyeSlash: Painter @Composable get() = painterResource(R.drawable.sf_eye_slash)
    val CloudSlash: Painter @Composable get() = painterResource(R.drawable.sf_icloud_slash)
    val PersonQuestionMark: Painter @Composable get() = rememberVectorPainter(AppVectors.PersonQuestionMark)
    val XCircle: Painter @Composable get() = painterResource(R.drawable.sf_xmark_circle_fill)
    val Gauge: Painter @Composable get() = painterResource(R.drawable.sf_gauge)
    val Building: Painter @Composable get() = rememberVectorPainter(AppVectors.Building)
    val PersonPlus: Painter @Composable get() = painterResource(R.drawable.sf_person_badge_plus)
    val PersonCropCircleBadgePlus: Painter @Composable get() = painterResource(R.drawable.sf_person_crop_circle_badge_plus)
    val PersonTextRectangle: Painter @Composable get() = painterResource(R.drawable.sf_person_crop_rectangle)
    val Crown: Painter @Composable get() = rememberVectorPainter(AppVectors.Crown)
    val PersonXmark: Painter @Composable get() = painterResource(R.drawable.sf_person_crop_circle_badge_xmark)
    val Key: Painter @Composable get() = rememberVectorPainter(AppVectors.Key)
    val Calendar: Painter @Composable get() = painterResource(R.drawable.sf_calendar)
    val History: Painter @Composable get() = painterResource(R.drawable.sf_arrow_counterclockwise)
    val Waveform: Painter @Composable get() = painterResource(R.drawable.sf_waveform)
    val FigureStand: Painter @Composable get() = rememberVectorPainter(AppVectors.FigureStand)
    val FigureStandDress: Painter @Composable get() = rememberVectorPainter(AppVectors.FigureStandDress)
    val Location: Painter @Composable get() = painterResource(R.drawable.sf_location_fill)
    val Drop: Painter @Composable get() = rememberVectorPainter(AppVectors.Drop)
    val Moon: Painter @Composable get() = painterResource(R.drawable.sf_moon_fill)
    val Eyedropper: Painter @Composable get() = painterResource(R.drawable.sf_eyedropper)
    val Plus: Painter @Composable get() = painterResource(R.drawable.sf_plus)
    val Dice: Painter @Composable get() = rememberVectorPainter(AppVectors.Dice)
    val Camera: Painter @Composable get() = painterResource(R.drawable.sf_camera_fill)
    val Gamepad: Painter @Composable get() = painterResource(R.drawable.sf_gamecontroller_fill)
    val Sliders: Painter @Composable get() = painterResource(R.drawable.sf_slider_horizontal_3)
    val Mug: Painter @Composable get() = rememberVectorPainter(AppVectors.Mug)
    val Cup: Painter @Composable get() = rememberVectorPainter(AppVectors.Cup)
    val ForkKnife: Painter @Composable get() = rememberVectorPainter(AppVectors.ForkKnife)
    val Wind: Painter @Composable get() = painterResource(R.drawable.sf_wind)
    val Heart: Painter @Composable get() = painterResource(R.drawable.sf_heart_fill)
    val ArrowDown: Painter @Composable get() = painterResource(R.drawable.sf_arrow_down)
    val Equal: Painter @Composable get() = painterResource(R.drawable.sf_equal)
}
